

select 
    SUM(paid_order_num                      )
    ,SUM(paid_order_amt                      )
    ,SUM(discount_amt                        )
    ,SUM(postage                             )
    ,SUM(refund_order_num                    )
    ,SUM(refund_amt                          )
    ,SUM(refund_postage                      )
    ,SUM(refund_items_amt                    )
    ,SUM(net_sales                           )
    ,SUM(logistics_delivery_order_num        )
    ,SUM(logistics_delivery_goods_num        )
    ,SUM(logistics_delivery_order_amt        )
    ,SUM(self_pick_up_order_num              )
    ,SUM(self_pick_up_goods_num              )
    ,SUM(self_pick_up_order_amt              )
    ,SUM(estimate_inv_cost                   )
    ,SUM(estimate_gross_profit               )
    ,SUM(sales_return_num                    )
    ,SUM(sales_return_amt                    )
    ,SUM(sales_return_tax_excluded_amt       )
    ,SUM(sales_return_cost                   )
    ,SUM(sales_return_tax_excluded_cost      )
    ,SUM(sales_out_num                       )
    ,SUM(sales_out_amt                       )
    ,SUM(sales_out_tax_excluded_amt          )
    ,SUM(sales_out_cost                      )
    ,SUM(sales_out_tax_excluded_cost         )
    ,SUM(sales_inv_amt                       )
    ,SUM(sales_inv_cost                      )
    ,SUM(recharge_num                        )
    ,SUM(recharge_amt                        )
    ,SUM(new_customer_num                    )
    ,SUM(new_member_num                      )
    ,SUM(member_paid_order_amt               )
    ,SUM(prepaid_card_paid_amt               )
    ,SUM(total_member_num                    )
    ,SUM(total_customer_num                  )
    ,SUM(goods_visit_pv                      )
    ,SUM(goods_expo_pv                       )
    ,SUM(add_cart_goods_num                  )
    ,SUM(on_sale_goods_num                   )
    ,SUM(place_order_amt                     )
    ,SUM(pv                                  )
    ,SUM(pages_stay_seconds                  )
    ,SUM(refund_total_seconds                )
    ,SUM(refund_trans_num                    )
    ,SUM(refund_trans_num_from_buyer         )
    ,SUM(refund_trans_num_from_seller        )
    ,SUM(refund_trans_num_with_cs_involved   )
    ,SUM(refund_total_seconds_from_buyer     )
    ,SUM(paid_goods_num                      )
    ,SUM(placed_order_sku_cnt                )
    ,SUM(total_fans_uv                       )
    ,SUM(new_fans_uv                         )
    ,SUM(unfollow_fans_uv                    )
    ,SUM(net_increase_uv                     )
    ,SUM(visit_fans_uv                       )
    ,SUM(placed_cnt                          )
    ,SUM(gift_card_order_paid_amt            )
    ,COUNT(DISTINCT paid_customer_num                   )
    ,COUNT(DISTINCT paid_recharge_member_num            )
    ,COUNT(DISTINCT paid_member_num                     )
    ,COUNT(DISTINCT recharge_member_num                 )
    ,COUNT(DISTINCT goods_visit_uv                      )
    ,COUNT(DISTINCT goods_visited_num                   )
    ,COUNT(DISTINCT dongxiao_goods_num                  )
    ,COUNT(DISTINCT book_customer_num                   )
    ,COUNT(DISTINCT team_uv                             )
    ,COUNT(DISTINCT one_page_uv                         )
    ,COUNT(DISTINCT cart_customer_num                   )
from 
    dm_dc.retail_team_uniservice_v6
where 
    kdt_id = 90715435
AND 
    par >= '20200801'
